# NOTE: Generated By HttpRunner v4.2.0
# FROM: testcases/example.yml
from httprunner import HttpRunner, Config, Step, RunRequest


class TestCaseExample(HttpRunner):

    config = Config("Example").variables(
        **{"PROTOCOL": "https", "BASEURL": "www.example.com"}
    )

    teststeps = [
        Step(
            RunRequest("T00_Example")
            .get("${PROTOCOL}://${BASEURL}")
            .extract()
            .with_jmespath("<title>(.*)</title>", "title")
            .with_jmespath("<p>(.*)</p>", "paragraph")
            .validate()
            .assert_equal("status_code", 200)
        ),
    ]


if __name__ == "__main__":
    TestCaseExample().test_start()
